# Generated by Django 5.1.3 on 2024-11-26 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_emailverification_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailverification',
            options={'verbose_name_plural': 'Верификация почты'},
        ),
    ]
