# Generated by Django 5.1.3 on 2024-12-08 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=256)),
                ('address', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('basket_history', models.JSONField(default=dict)),
                ('status', models.SmallIntegerField(choices=[(0, 'создан'), (1, 'оплачен'), (2, 'в пути'), (3, 'доставлен')], default=0)),
                ('initiated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
