# Generated by Django 5.1.3 on 2024-12-10 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='initiated',
            new_name='initiator',
        ),
    ]
